import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LayoutHeader from "./layouts/LayoutHeader";
import LayoutFooter from "./layouts/LayoutFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let isLogin = true;
  return (
    <html lang="en">
      <body className={inter.className}>
        {isLogin ? <LayoutHeader/> : null}

        {children}
        
        <LayoutFooter/>
      </body>
    </html>
  );
}
